version: '3.8'

services:
  db:
    image: postgres

  redis:
    image: redis

  vote:
    image: voting-app
    ports:
      - "5000:80"
    depends_on:
      - redis

  result:
    image: result-app
    ports:
      - "5001:80"
    depends_on:
      - db

  worker:
    image: working-app
    depends_on:
      - db
      - redis
